bucket          = "roboshop-vpc"
key             = "frontend/dev/terraform.tfstate"
ENV             = "dev"
INSTANCE_TYPE      = "t3.small"
KEYPAIR_NAME       = "devops"
component          = "mongodb"